### ISSUE TITLE
Hardening of the Firewall

### ISSUE THREAD

**Issue by ks-ialvarez** [ks-cspr/network-infra#5]

**Comment by z-caudroy** [comment]
@ks-ialvarez  Deactivate options that we dont use, followed recommendations of fortinet in terms of security, cleaned all security policies, configured log and created admin account for administrators.
TODO: After measurements with @ks-cajoto and developers need to adjust maybe settings or change FW.

**Comment by ks-ialvarez** [comment]
If all that could be done is done, let's close this. About the measurements, this would be a task for next weeks. Sending you an email so we don't forget.

Closing.
